### ISSUE TITLE
No encoder has been configured for account "App\Entity\User".

### ISSUE THREAD

**Issue by miramir** [thecodingmachine/symfony-vuejs#1]
php bin/console doctrine:fixtures:load

Эту команду надо выполнять уже после изменения файла config/packages/security.yaml ,
иначе это приводит к ошибке в заголовке

**Comment by gulien** [comment]
You're right, the fixtures should be loaded after having updated the file `security.yaml`!

**Comment by gulien** [comment]
This has been fixed in the latest version of the tutorial 😄Thank you!
