### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by iliyaZelenko** [thecodingmachine/symfony-vuejs#11]
I think you failed by adding these dependencies to the `devDependencies`:

```bash
yarn add --dev vue-router axios vuex
```

You should install them as a `dependencies` because you use them in your application, not only as a dev tools.

**Comment by gulien** [comment]
It depends, because overall all npm dependencies are used for building the resulting `js` file which contains everything.

**Comment by iliyaZelenko** [comment]
I do not agree that this is correct and noticed that most of people do not do it like you, decide for yourself.
