### ISSUE TITLE
render static pages (no js browsers support)

### ISSUE THREAD

**Issue by sashsvamir** [thecodingmachine/symfony-vuejs#2]
Thanks for great Symfony/Vuejs example!
But what if i want be sure to my app was indexed by google?
Can this app render static pages?

**Comment by gulien** [comment]
It is possible to improve the SEO of your website using various tips (https://snipcart.com/blog/vue-js-seo-prerender-example).

You may also render static pages by making your app accessible for instance only on URL starting with /app. Everything else (/api/* excluded) will be handler by Symfony in a more traditional way!
