### ISSUE TITLE
Symfony Plugin Configuration

### ISSUE THREAD

**Issue by thedomeffm** [thecodingmachine/symfony-vuejs#27]
Hi,
great work - thx for sharing.

I am using PHPStorm and use the Symfony Plugin, but I don't know how to configure the plugin when Symfony is not in root dir of the project, but in a sub dir.

![symfony-vuejs-symfony-plugin-config](https://user-images.githubusercontent.com/29406401/63679844-978b1b80-c7f2-11e9-9d50-f5fde060022e.png)

Greetings,
Dome

**Comment by gulien** [comment]
Hello @thedomeffm!

I've never use the Symfony Plugin, so I dunno how to do that 🤔
