### ISSUE TITLE
plainPassword and password encoding

### ISSUE THREAD

**Issue by vandroids** [thecodingmachine/symfony-vuejs#3]
Hi!

In your code there is a line:
```
// necessary to force the update to see the change
$em->getUnitOfWork()->recomputeSingleEntityChangeSet($meta, $entity);
```

I don't quite understand what's the purpose of this code?

Also in a User entity you have method `eraseCredentials()`, but it never gets invoked. When should I use it?

**Comment by gulien** [comment]
Not sure about this code line: it comes from a tutorial I'd read (and I cannot remember its name).

The method `eraseCredentials()` comes from the `UserInterface`. It used internally by Symofny.
